services:
  app:
    image: node:22.14.0-alpine3.21
    container_name: typescript-api
    ports:
      - "8090:8090"
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    environment:
      - NODE_ENV=development
    command: sh -c "npm install -g typescript && tail -f /dev/null"
    networks:
      - api

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_DATABASE:-api}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  postgres_data:
    driver: local
