services:
  app:
    image: node:22.14.0-alpine3.21
    container_name: typescript-api
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    environment:
      - NODE_ENV=development
    command: sh -c "npm install -g typescript && tail -f /dev/null"
